# Meta
title: Shakespeare Programming Language
description: Where the empty vessel makes the loudest sound.

# URLs
baseurl: ""
url: "http://shakespearelang.org"

# Footer
copyright:
  text: Miles Zimmerman
  link: http://maztek.io/

# Build settings
markdown:    kramdown
highlighter: pygments