# Meta
title: Shakespeare Programming Language
description: Where the empty vessel makes the loudest sound.
author: Miles Zimmerman

# URLs
baseurl: ""
url: "http://shakespearelang.org"

# Footer
copyright:
  text: Miles Zimmerman
  link: http://maztek.io/
  year: 2014

# Build settings
markdown:    kramdown
highlighter: pygments